/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.stickynotes.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.stickynotes.model.stickyNote;

import com.stickynotes.service.persistence.stickyNotePersistence;
import com.stickynotes.service.stickyNoteLocalService;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the sticky note local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.stickynotes.service.impl.stickyNoteLocalServiceImpl}.
 * </p>
 *
 * @author mbelda
 * @see com.stickynotes.service.impl.stickyNoteLocalServiceImpl
 * @see com.stickynotes.service.stickyNoteLocalServiceUtil
 * @generated
 */
public abstract class stickyNoteLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements stickyNoteLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.stickynotes.service.stickyNoteLocalServiceUtil} to access the sticky note local service.
	 */

	/**
	 * Adds the sticky note to the database. Also notifies the appropriate model listeners.
	 *
	 * @param stickyNote the sticky note
	 * @return the sticky note that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public stickyNote addstickyNote(stickyNote stickyNote)
		throws SystemException {
		stickyNote.setNew(true);

		return stickyNotePersistence.update(stickyNote, false);
	}

	/**
	 * Creates a new sticky note with the primary key. Does not add the sticky note to the database.
	 *
	 * @param stickyNoteId the primary key for the new sticky note
	 * @return the new sticky note
	 */
	public stickyNote createstickyNote(long stickyNoteId) {
		return stickyNotePersistence.create(stickyNoteId);
	}

	/**
	 * Deletes the sticky note with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param stickyNoteId the primary key of the sticky note
	 * @return the sticky note that was removed
	 * @throws PortalException if a sticky note with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public stickyNote deletestickyNote(long stickyNoteId)
		throws PortalException, SystemException {
		return stickyNotePersistence.remove(stickyNoteId);
	}

	/**
	 * Deletes the sticky note from the database. Also notifies the appropriate model listeners.
	 *
	 * @param stickyNote the sticky note
	 * @return the sticky note that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public stickyNote deletestickyNote(stickyNote stickyNote)
		throws SystemException {
		return stickyNotePersistence.remove(stickyNote);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(stickyNote.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return stickyNotePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return stickyNotePersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return stickyNotePersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return stickyNotePersistence.countWithDynamicQuery(dynamicQuery);
	}

	public stickyNote fetchstickyNote(long stickyNoteId)
		throws SystemException {
		return stickyNotePersistence.fetchByPrimaryKey(stickyNoteId);
	}

	/**
	 * Returns the sticky note with the primary key.
	 *
	 * @param stickyNoteId the primary key of the sticky note
	 * @return the sticky note
	 * @throws PortalException if a sticky note with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public stickyNote getstickyNote(long stickyNoteId)
		throws PortalException, SystemException {
		return stickyNotePersistence.findByPrimaryKey(stickyNoteId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return stickyNotePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the sticky notes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of sticky notes
	 * @param end the upper bound of the range of sticky notes (not inclusive)
	 * @return the range of sticky notes
	 * @throws SystemException if a system exception occurred
	 */
	public List<stickyNote> getstickyNotes(int start, int end)
		throws SystemException {
		return stickyNotePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of sticky notes.
	 *
	 * @return the number of sticky notes
	 * @throws SystemException if a system exception occurred
	 */
	public int getstickyNotesCount() throws SystemException {
		return stickyNotePersistence.countAll();
	}

	/**
	 * Updates the sticky note in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param stickyNote the sticky note
	 * @return the sticky note that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public stickyNote updatestickyNote(stickyNote stickyNote)
		throws SystemException {
		return updatestickyNote(stickyNote, true);
	}

	/**
	 * Updates the sticky note in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param stickyNote the sticky note
	 * @param merge whether to merge the sticky note with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the sticky note that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public stickyNote updatestickyNote(stickyNote stickyNote, boolean merge)
		throws SystemException {
		stickyNote.setNew(false);

		return stickyNotePersistence.update(stickyNote, merge);
	}

	/**
	 * Returns the sticky note local service.
	 *
	 * @return the sticky note local service
	 */
	public stickyNoteLocalService getstickyNoteLocalService() {
		return stickyNoteLocalService;
	}

	/**
	 * Sets the sticky note local service.
	 *
	 * @param stickyNoteLocalService the sticky note local service
	 */
	public void setstickyNoteLocalService(
		stickyNoteLocalService stickyNoteLocalService) {
		this.stickyNoteLocalService = stickyNoteLocalService;
	}

	/**
	 * Returns the sticky note persistence.
	 *
	 * @return the sticky note persistence
	 */
	public stickyNotePersistence getstickyNotePersistence() {
		return stickyNotePersistence;
	}

	/**
	 * Sets the sticky note persistence.
	 *
	 * @param stickyNotePersistence the sticky note persistence
	 */
	public void setstickyNotePersistence(
		stickyNotePersistence stickyNotePersistence) {
		this.stickyNotePersistence = stickyNotePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.stickynotes.model.stickyNote",
			stickyNoteLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.stickynotes.model.stickyNote");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return stickyNote.class;
	}

	protected String getModelClassName() {
		return stickyNote.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = stickyNotePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = stickyNoteLocalService.class)
	protected stickyNoteLocalService stickyNoteLocalService;
	@BeanReference(type = stickyNotePersistence.class)
	protected stickyNotePersistence stickyNotePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private stickyNoteLocalServiceClpInvoker _clpInvoker = new stickyNoteLocalServiceClpInvoker();
}